# Code for my first q-learning journey

In [3]:
import numpy as np

In [4]:
# q is the tabular representation for q func
q = np.matrix(np.zeros([6, 6]))

# r is the tabular representation for rewards
# r is predefined and remains unchanged
r = np.matrix([
    [-1, -1, -1, -1, 0, -1],
    [-1, -1, -1,  0, -1, 100],
    [-1, -1, -1,  0, -1,  -1],
    [-1,  0,  0, -1,  0,  -1],
    [ 0, -1, -1,  0, -1, 100],
    [-1,  0, -1, -1,  0, 100]])

# hyper-parameter
gamma = 0.8
epsilon = 0.4

In [8]:
# the main training loop
for episode in range(101):
    # random initial state
    state = np.random.randint(0, 6)
    while (state != 5): # stop only when state is TERMINAL
        # Filter feasible actions.
        # Even in random case, we cannot choose actions whose r[state, action] = -1
        # It's not about RL. these actions are not feasible pysically

        possible_actions = []
        possible_q = []
        for action in range(6):
            if r[state, action] >= 0:
                possible_actions.append(action)
                possible_q.append(q[state, action])

        # tep next state, here we use epsilon-greedy algorithm
        action = -1
        if np.random.random() < epsilon:
            # choose random action
            action = possible_actions[np.random.randint(0, len(possible_actions))]
        else:
            # greedy
            action = possible_actions[np.argmax(possible_q)]

        # Update q value
        q[state, action] = r[state, action] + gamma * q[action].max()

        # Go to the next state
        state = action

    # Display training track
    if episode % 10 == 0:
        print("------------------------------------------------")
        print("Training episode: %d" % episode)
        print(q)

------------------------------------------------
Training episode: 0
[[  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0. 100.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]]
------------------------------------------------
Training episode: 10
[[  0.   0.   0.   0.  80.   0.]
 [  0.   0.   0.  64.   0. 100.]
 [  0.   0.   0.  64.   0.   0.]
 [  0.  80.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0. 100.]
 [  0.   0.   0.   0.   0.   0.]]
------------------------------------------------
Training episode: 20
[[  0.    0.    0.    0.   80.    0. ]
 [  0.    0.    0.   64.    0.  100. ]
 [  0.    0.    0.   64.    0.    0. ]
 [  0.   80.   51.2   0.   80.    0. ]
 [  0.    0.    0.    0.    0.  100. ]
 [  0.    0.    0.    0.    0.    0. ]]
------------------------------------------------
Training episode: 30
[[  0.    0.    0.    0.   80.    0. ]
 [  0.    0.    0.   64.    0.  100. ]
 [  0.    

In [9]:
# verify
for i in range(10):
    # one episode
    print('episode: %d' % i)

    # random initial state
    state = np.random.randint(0, 6)
    print('the robot borns in %d.' % state)
    for _ in range(20):
        if state == 5:
            break
        action = np.argmax(q[state])
        print('the robot goes to %d.' % action)
        state = action

episode: 0
the robot borns in 4.
the robot goes to 5.
episode: 1
the robot borns in 3.
the robot goes to 1.
the robot goes to 5.
episode: 2
the robot borns in 4.
the robot goes to 5.
episode: 3
the robot borns in 2.
the robot goes to 3.
the robot goes to 1.
the robot goes to 5.
episode: 4
the robot borns in 5.
episode: 5
the robot borns in 2.
the robot goes to 3.
the robot goes to 1.
the robot goes to 5.
episode: 6
the robot borns in 4.
the robot goes to 5.
episode: 7
the robot borns in 2.
the robot goes to 3.
the robot goes to 1.
the robot goes to 5.
episode: 8
the robot borns in 1.
the robot goes to 5.
episode: 9
the robot borns in 3.
the robot goes to 1.
the robot goes to 5.
